// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: components.sql

package sqlcdb

import (
	"context"
)

const getComponent = `-- name: GetComponent :one
SELECT id, display_name, description, owner_pod, paths, last_updated, metadata FROM components WHERE id = ? LIMIT 1
`

func (q *Queries) GetComponent(ctx context.Context, id string) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Description,
		&i.OwnerPod,
		&i.Paths,
		&i.LastUpdated,
		&i.Metadata,
	)
	return i, err
}
