// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (pod_id, workstream_id, event_type, payload, occurred_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	PodID        sql.NullString  `json:"pod_id"`
	WorkstreamID sql.NullString  `json:"workstream_id"`
	EventType    string          `json:"event_type"`
	Payload      json.RawMessage `json:"payload"`
	OccurredAt   time.Time       `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.PodID,
		arg.WorkstreamID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
