// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gaps.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const acknowledgeGap = `-- name: AcknowledgeGap :exec
UPDATE capability_gaps SET status = 'acknowledged' WHERE id = ?
`

func (q *Queries) AcknowledgeGap(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, acknowledgeGap, id)
	return err
}

const createGap = `-- name: CreateGap :exec
INSERT INTO capability_gaps (
  id, pod_id, workstream_id, category, description, priority, status,
  resolution_ref, frequency, scope, occurred_at, resolved_at, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGapParams struct {
	ID            string          `json:"id"`
	PodID         string          `json:"pod_id"`
	WorkstreamID  sql.NullString  `json:"workstream_id"`
	Category      string          `json:"category"`
	Description   string          `json:"description"`
	Priority      int64           `json:"priority"`
	Status        string          `json:"status"`
	ResolutionRef sql.NullString  `json:"resolution_ref"`
	Frequency     int64           `json:"frequency"`
	Scope         string          `json:"scope"`
	OccurredAt    time.Time       `json:"occurred_at"`
	ResolvedAt    sql.NullTime    `json:"resolved_at"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateGap(ctx context.Context, arg CreateGapParams) error {
	_, err := q.db.ExecContext(ctx, createGap,
		arg.ID,
		arg.PodID,
		arg.WorkstreamID,
		arg.Category,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.ResolutionRef,
		arg.Frequency,
		arg.Scope,
		arg.OccurredAt,
		arg.ResolvedAt,
		arg.Metadata,
	)
	return err
}

const getGap = `-- name: GetGap :one
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps WHERE id = ? LIMIT 1
`

func (q *Queries) GetGap(ctx context.Context, id string) (CapabilityGap, error) {
	row := q.db.QueryRowContext(ctx, getGap, id)
	var i CapabilityGap
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.WorkstreamID,
		&i.Category,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.ResolutionRef,
		&i.Frequency,
		&i.Scope,
		&i.OccurredAt,
		&i.ResolvedAt,
		&i.Metadata,
	)
	return i, err
}

const getGapByPodAndDescription = `-- name: GetGapByPodAndDescription :one
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps
WHERE pod_id = ? AND description = ?
LIMIT 1
`

type GetGapByPodAndDescriptionParams struct {
	PodID       string `json:"pod_id"`
	Description string `json:"description"`
}

func (q *Queries) GetGapByPodAndDescription(ctx context.Context, arg GetGapByPodAndDescriptionParams) (CapabilityGap, error) {
	row := q.db.QueryRowContext(ctx, getGapByPodAndDescription, arg.PodID, arg.Description)
	var i CapabilityGap
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.WorkstreamID,
		&i.Category,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.ResolutionRef,
		&i.Frequency,
		&i.Scope,
		&i.OccurredAt,
		&i.ResolvedAt,
		&i.Metadata,
	)
	return i, err
}

const getOpenGapByPodAndDescription = `-- name: GetOpenGapByPodAndDescription :one
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps
WHERE pod_id = ? AND description = ? AND status = 'open'
LIMIT 1
`

type GetOpenGapByPodAndDescriptionParams struct {
	PodID       string `json:"pod_id"`
	Description string `json:"description"`
}

func (q *Queries) GetOpenGapByPodAndDescription(ctx context.Context, arg GetOpenGapByPodAndDescriptionParams) (CapabilityGap, error) {
	row := q.db.QueryRowContext(ctx, getOpenGapByPodAndDescription, arg.PodID, arg.Description)
	var i CapabilityGap
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.WorkstreamID,
		&i.Category,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.ResolutionRef,
		&i.Frequency,
		&i.Scope,
		&i.OccurredAt,
		&i.ResolvedAt,
		&i.Metadata,
	)
	return i, err
}

const incrementGapFrequency = `-- name: IncrementGapFrequency :exec
UPDATE capability_gaps
SET frequency = frequency + 1, occurred_at = ?
WHERE id = ?
`

type IncrementGapFrequencyParams struct {
	OccurredAt time.Time `json:"occurred_at"`
	ID         string    `json:"id"`
}

func (q *Queries) IncrementGapFrequency(ctx context.Context, arg IncrementGapFrequencyParams) error {
	_, err := q.db.ExecContext(ctx, incrementGapFrequency, arg.OccurredAt, arg.ID)
	return err
}

const listGapsAll = `-- name: ListGapsAll :many
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps ORDER BY priority ASC, occurred_at DESC
`

func (q *Queries) ListGapsAll(ctx context.Context) ([]CapabilityGap, error) {
	rows, err := q.db.QueryContext(ctx, listGapsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityGap
	for rows.Next() {
		var i CapabilityGap
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.WorkstreamID,
			&i.Category,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.ResolutionRef,
			&i.Frequency,
			&i.Scope,
			&i.OccurredAt,
			&i.ResolvedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGapsByPod = `-- name: ListGapsByPod :many
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps WHERE pod_id = ? ORDER BY priority ASC, occurred_at DESC
`

func (q *Queries) ListGapsByPod(ctx context.Context, podID string) ([]CapabilityGap, error) {
	rows, err := q.db.QueryContext(ctx, listGapsByPod, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityGap
	for rows.Next() {
		var i CapabilityGap
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.WorkstreamID,
			&i.Category,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.ResolutionRef,
			&i.Frequency,
			&i.Scope,
			&i.OccurredAt,
			&i.ResolvedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGapsByPod = `-- name: ListOpenGapsByPod :many
SELECT id, pod_id, workstream_id, category, description, priority, status, resolution_ref, frequency, scope, occurred_at, resolved_at, metadata FROM capability_gaps
WHERE pod_id = ? AND status = 'open'
ORDER BY priority ASC, occurred_at DESC
`

func (q *Queries) ListOpenGapsByPod(ctx context.Context, podID string) ([]CapabilityGap, error) {
	rows, err := q.db.QueryContext(ctx, listOpenGapsByPod, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityGap
	for rows.Next() {
		var i CapabilityGap
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.WorkstreamID,
			&i.Category,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.ResolutionRef,
			&i.Frequency,
			&i.Scope,
			&i.OccurredAt,
			&i.ResolvedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveGap = `-- name: ResolveGap :exec
UPDATE capability_gaps
SET status = 'resolved', resolved_at = ?, resolution_ref = ?
WHERE id = ?
`

type ResolveGapParams struct {
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
	ResolutionRef sql.NullString `json:"resolution_ref"`
	ID            string         `json:"id"`
}

func (q *Queries) ResolveGap(ctx context.Context, arg ResolveGapParams) error {
	_, err := q.db.ExecContext(ctx, resolveGap, arg.ResolvedAt, arg.ResolutionRef, arg.ID)
	return err
}
