// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CapabilityGap struct {
	ID            string          `json:"id"`
	PodID         string          `json:"pod_id"`
	WorkstreamID  sql.NullString  `json:"workstream_id"`
	Category      string          `json:"category"`
	Description   string          `json:"description"`
	Priority      int64           `json:"priority"`
	Status        string          `json:"status"`
	ResolutionRef sql.NullString  `json:"resolution_ref"`
	Frequency     int64           `json:"frequency"`
	Scope         string          `json:"scope"`
	OccurredAt    time.Time       `json:"occurred_at"`
	ResolvedAt    sql.NullTime    `json:"resolved_at"`
	Metadata      json.RawMessage `json:"metadata"`
}

type Component struct {
	ID          string          `json:"id"`
	DisplayName string          `json:"display_name"`
	Description sql.NullString  `json:"description"`
	OwnerPod    sql.NullString  `json:"owner_pod"`
	Paths       json.RawMessage `json:"paths"`
	LastUpdated time.Time       `json:"last_updated"`
	Metadata    json.RawMessage `json:"metadata"`
}

type DecisionIndex struct {
	ID         string          `json:"id"`
	Path       string          `json:"path"`
	Title      string          `json:"title"`
	Components json.RawMessage `json:"components"`
	DecidedBy  string          `json:"decided_by"`
	DecidedAt  time.Time       `json:"decided_at"`
	Scope      string          `json:"scope"`
	Metadata   json.RawMessage `json:"metadata"`
}

type Event struct {
	ID           int64           `json:"id"`
	PodID        sql.NullString  `json:"pod_id"`
	WorkstreamID sql.NullString  `json:"workstream_id"`
	EventType    string          `json:"event_type"`
	Payload      json.RawMessage `json:"payload"`
	OccurredAt   time.Time       `json:"occurred_at"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Pod struct {
	ID          string          `json:"id"`
	DisplayName string          `json:"display_name"`
	Owner       string          `json:"owner"`
	PublicKey   sql.NullString  `json:"public_key"`
	CreatedAt   time.Time       `json:"created_at"`
	Active      bool            `json:"active"`
	Metadata    json.RawMessage `json:"metadata"`
}

type QualityGateIndex struct {
	ID          string          `json:"id"`
	Path        string          `json:"path"`
	Scope       string          `json:"scope"`
	TargetPods  json.RawMessage `json:"target_pods"`
	Enabled     bool            `json:"enabled"`
	LastUpdated time.Time       `json:"last_updated"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	AppliedAt time.Time `json:"applied_at"`
}

type SpecIndex struct {
	ID             string          `json:"id"`
	Path           string          `json:"path"`
	CurrentVersion string          `json:"current_version"`
	Status         string          `json:"status"`
	OwnerPod       sql.NullString  `json:"owner_pod"`
	Scope          string          `json:"scope"`
	Components     json.RawMessage `json:"components"`
	Dependents     json.RawMessage `json:"dependents"`
	LastUpdated    time.Time       `json:"last_updated"`
	Metadata       json.RawMessage `json:"metadata"`
}

type Subscription struct {
	ID         string         `json:"id"`
	PodID      string         `json:"pod_id"`
	FilterExpr string         `json:"filter_expr"`
	Delivery   string         `json:"delivery"`
	WebhookUrl sql.NullString `json:"webhook_url"`
	Active     bool           `json:"active"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Workstream struct {
	ID           string          `json:"id"`
	PodID        string          `json:"pod_id"`
	Title        string          `json:"title"`
	Intent       sql.NullString  `json:"intent"`
	Status       string          `json:"status"`
	SpecRef      sql.NullString  `json:"spec_ref"`
	Branch       sql.NullString  `json:"branch"`
	Components   json.RawMessage `json:"components"`
	Scope        string          `json:"scope"`
	LastActivity time.Time       `json:"last_activity"`
	CreatedAt    time.Time       `json:"created_at"`
	Metadata     json.RawMessage `json:"metadata"`
}
