// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pods.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createPod = `-- name: CreatePod :exec
INSERT INTO pods (id, display_name, owner, public_key, created_at, active, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePodParams struct {
	ID          string          `json:"id"`
	DisplayName string          `json:"display_name"`
	Owner       string          `json:"owner"`
	PublicKey   sql.NullString  `json:"public_key"`
	CreatedAt   time.Time       `json:"created_at"`
	Active      bool            `json:"active"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreatePod(ctx context.Context, arg CreatePodParams) error {
	_, err := q.db.ExecContext(ctx, createPod,
		arg.ID,
		arg.DisplayName,
		arg.Owner,
		arg.PublicKey,
		arg.CreatedAt,
		arg.Active,
		arg.Metadata,
	)
	return err
}

const getPod = `-- name: GetPod :one
SELECT id, display_name, owner, public_key, created_at, active, metadata FROM pods WHERE id = ? LIMIT 1
`

func (q *Queries) GetPod(ctx context.Context, id string) (Pod, error) {
	row := q.db.QueryRowContext(ctx, getPod, id)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Owner,
		&i.PublicKey,
		&i.CreatedAt,
		&i.Active,
		&i.Metadata,
	)
	return i, err
}

const getPodByDisplayName = `-- name: GetPodByDisplayName :one
SELECT id, display_name, owner, public_key, created_at, active, metadata FROM pods WHERE display_name = ? LIMIT 1
`

func (q *Queries) GetPodByDisplayName(ctx context.Context, displayName string) (Pod, error) {
	row := q.db.QueryRowContext(ctx, getPodByDisplayName, displayName)
	var i Pod
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Owner,
		&i.PublicKey,
		&i.CreatedAt,
		&i.Active,
		&i.Metadata,
	)
	return i, err
}

const listPods = `-- name: ListPods :many
SELECT id, display_name, owner, public_key, created_at, active, metadata FROM pods ORDER BY created_at ASC
`

func (q *Queries) ListPods(ctx context.Context) ([]Pod, error) {
	rows, err := q.db.QueryContext(ctx, listPods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pod
	for rows.Next() {
		var i Pod
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Owner,
			&i.PublicKey,
			&i.CreatedAt,
			&i.Active,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
