// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workstreams.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createWorkstream = `-- name: CreateWorkstream :exec
INSERT INTO workstreams (
  id, pod_id, title, intent, status, spec_ref, branch, components,
  scope, last_activity, created_at, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkstreamParams struct {
	ID           string          `json:"id"`
	PodID        string          `json:"pod_id"`
	Title        string          `json:"title"`
	Intent       sql.NullString  `json:"intent"`
	Status       string          `json:"status"`
	SpecRef      sql.NullString  `json:"spec_ref"`
	Branch       sql.NullString  `json:"branch"`
	Components   json.RawMessage `json:"components"`
	Scope        string          `json:"scope"`
	LastActivity time.Time       `json:"last_activity"`
	CreatedAt    time.Time       `json:"created_at"`
	Metadata     json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateWorkstream(ctx context.Context, arg CreateWorkstreamParams) error {
	_, err := q.db.ExecContext(ctx, createWorkstream,
		arg.ID,
		arg.PodID,
		arg.Title,
		arg.Intent,
		arg.Status,
		arg.SpecRef,
		arg.Branch,
		arg.Components,
		arg.Scope,
		arg.LastActivity,
		arg.CreatedAt,
		arg.Metadata,
	)
	return err
}

const getWorkstream = `-- name: GetWorkstream :one
SELECT id, pod_id, title, intent, status, spec_ref, branch, components, scope, last_activity, created_at, metadata FROM workstreams WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkstream(ctx context.Context, id string) (Workstream, error) {
	row := q.db.QueryRowContext(ctx, getWorkstream, id)
	var i Workstream
	err := row.Scan(
		&i.ID,
		&i.PodID,
		&i.Title,
		&i.Intent,
		&i.Status,
		&i.SpecRef,
		&i.Branch,
		&i.Components,
		&i.Scope,
		&i.LastActivity,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const listActiveWorkstreamsByPod = `-- name: ListActiveWorkstreamsByPod :many
SELECT id, pod_id, title, intent, status, spec_ref, branch, components, scope, last_activity, created_at, metadata FROM workstreams
WHERE pod_id = ? AND status IN ('planning', 'active', 'blocked', 'review')
ORDER BY last_activity DESC
`

func (q *Queries) ListActiveWorkstreamsByPod(ctx context.Context, podID string) ([]Workstream, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkstreamsByPod, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workstream
	for rows.Next() {
		var i Workstream
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.Title,
			&i.Intent,
			&i.Status,
			&i.SpecRef,
			&i.Branch,
			&i.Components,
			&i.Scope,
			&i.LastActivity,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkstreamsByPod = `-- name: ListWorkstreamsByPod :many
SELECT id, pod_id, title, intent, status, spec_ref, branch, components, scope, last_activity, created_at, metadata FROM workstreams WHERE pod_id = ? ORDER BY last_activity DESC
`

func (q *Queries) ListWorkstreamsByPod(ctx context.Context, podID string) ([]Workstream, error) {
	rows, err := q.db.QueryContext(ctx, listWorkstreamsByPod, podID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workstream
	for rows.Next() {
		var i Workstream
		if err := rows.Scan(
			&i.ID,
			&i.PodID,
			&i.Title,
			&i.Intent,
			&i.Status,
			&i.SpecRef,
			&i.Branch,
			&i.Components,
			&i.Scope,
			&i.LastActivity,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchWorkstreamActivity = `-- name: TouchWorkstreamActivity :exec
UPDATE workstreams SET last_activity = ? WHERE id = ?
`

type TouchWorkstreamActivityParams struct {
	LastActivity time.Time `json:"last_activity"`
	ID           string    `json:"id"`
}

func (q *Queries) TouchWorkstreamActivity(ctx context.Context, arg TouchWorkstreamActivityParams) error {
	_, err := q.db.ExecContext(ctx, touchWorkstreamActivity, arg.LastActivity, arg.ID)
	return err
}

const updateWorkstreamStatus = `-- name: UpdateWorkstreamStatus :exec
UPDATE workstreams SET status = ?, last_activity = ? WHERE id = ?
`

type UpdateWorkstreamStatusParams struct {
	Status       string    `json:"status"`
	LastActivity time.Time `json:"last_activity"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateWorkstreamStatus(ctx context.Context, arg UpdateWorkstreamStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkstreamStatus, arg.Status, arg.LastActivity, arg.ID)
	return err
}
